cmd: npm test
targets:
  PreTest:
      cmd: "npm run pretest"
  TestSuite:
      cmd: "npm run test"
  ContinuesTest:
      cmd: "mocha -w tests/index.js"
  Publsh:
      cmd: "npm test && npm run cbuild -- -o dist/correntlynote.js && npm publish"
